about_tab_id = "ABOUT"
about_main_title_id = "Optimise your car with Chip tuning"
about_main_text1_id = "Chip tuning is an updating process in the electronic control unit (ECU) of a vehicle for a better performance, fuel efficiency and cleaner emissions."
about_main_text2_id = "This performance chip increases radically your horsepower.It doesn't damage your engine, on the contrary it is designed to work in a healthy and sustainable way for your car, regardless of whether it is petrol or diesel. It is proven: features such as running smoothness or vibrations in the transition or at start-up improve rapidly."
your_id = "Your car needs a remapping"
your_text_id = "Also called Remapping (ECO REMAP), chiptuning offers lots of optiones to make your car develops a high level of performance and capacity at a technological level to fit into the future. Any car with any brand could be reprogrammed to turn in an improved version, which provides for example smooth running or breaking factory power limitations."
works_id = "How does Chip Tuning works?"
works_text_id = "These modifications or adjustments are contained in chip tuning files. Each is designed and generated by experienced engineers, programmers and tuners."
works_text2_id = "The chip tuning files are also called calibration files, and its content, personalised for the client, is created and ready to be installed and activated in their ECU's car. Basically the files unblock automatically your car's actual potential."
install_id = "How Chip tuning is installed?"
install_text_id = "With a programmer device (BDM, EOBD, EOBD CAN-BUS, K-LINE, PWM EOBD) previously set up, is connected between your ECU and the sensor system. Is doesn't need to open the control unit r touch any other element of the car. The exchange of data takes place when the small device is connected."
install_text2_id = "The device works as a microprocessor and it is compatible with any ECU of any car. Nothing will be deconfigured or unsettled, it will improve the factory settings of the engine."


serv_tab_title_id = "SERVICES"
file_title_id = "Chip tuning Files"
file_text_id = "The chip tuning files are 100% personalised, with the best performance, adapted for you, which brings less fuel consumption and a safe engine reassignment. All this turns into a real benefit thanks to the chip optimisation work." 
soft_optim_title_id = "Software optimization"
soft_optim_text1_id = "Engine software optimisation is developed to create a more powerful car through the act of chip tuning. Tuning the software of your engine and gearbox means to add a enormous value for your car in long term."
# soft_optim_text2_id = "It is proven: features such as running smoothness or vibrations in the transition or at start-up improve rapidly"
dyno_title_id = "Dyno-Road Test"
dyno_text1_id = "It is a road test bench that measures power, torque, acceleration and other parameters of passenger cars and other combustion or electric vehicles. You will simulate special load situations with our dyno-road equipment, in order to guarante estability of your vehicle."
dyno_text2_id = "We analyze with our dynamometer your driving behavior of the car through extensive road tests – so that comfort and performance fit together. With this service we will be able to know what to do next, in order to maximize your vehicle´s power and to be able to diagnose to adjustments you need."
device_inst_title_id = "Device installation at home"
device_inst_text1_id = "Are our facilities too far away for you? We make things easy with our customers' convenience in mind. Order the desired and most suitable system for self-assembly or even use our growing network of tuners for installation in your area."
device_inst_text2_id = "We can also drive to you and optimise your car directly in your garage. It will only be needed power and wifi connection. If your car is standingmost of the time, or in different locations, we adapt ourselves to bring you the best service."
device_inst_text3_id = "* We are also aware of the importance of respecting sanitary measures when carrying out a home service, taking into account the safety, hygiene and protection necessary due to the Coronavirus."


why_title_id = "Who we are"
why_text1_id = "At AP-chip, a permanent growing team of experienced engineers, designers and mechanic proffesional workers work close together to offer the best custom software and delivery services."
why_text2_id = "Due to the continuous improvement, you can always benefit from our experience and team of expertise. Our development methods is based on our passion in cars and our dedication to learn and to implement the latest in technology for the vehicle of our clients."
why_text3_id = "With a full commitment, we look after you in every situation whether on the racetrack or on the road; with our individual support you are well prepared for every situation that your vehicle's performance will face."

become_tab_id = "BECOME A TUNER"
become_boxinfo1_id = "Worldwide chip tuning files services"
become_boxinfo2_id = "25 minutes service time"
become_boxinfo3_id = "1112 Customers"
become_boxinfo4_id = "19 tuners"
become_boxinfo5_id = "1200 files a month"
become_boxinfo6_id = "Powerful database"
become_boxinfo7_id = "The best ECU Remap"
become_boxinfo8_id = "Smart Solutions"
become_boxinfo9_id = "Professional Service"
become_boxinfo10_id = "Chip tuning files ECU modifications"


buy_title_id = "BUY TUNING FILES IN 4 QUICK, SAFE AND EASY STEPS"
buy_step1_title_id ="STEP 1: REGISTER"
buy_step1_text_id = "Register your account free of charge. Registration is obligatory if you want to upload and recieve chiptuning files"
buy_step2_title_id = "STEP 2: BUY TOKENS"
buy_step2_text_id = "Buy tuning Tokens safely using PayPal or credit card. Get your invoice straight away"
buy_step3_title_id = "STEP 3: OPEN FILE SERVICE"
buy_step3_text_id = "Find the file you need"
buy_step4_title_id = "STEP 4: DOWNLOAD IT"
buy_step4_text_id = "Download your modified chip tuning file"


price_title_id = "Prices "
pack1_title_id= "GTS"
contains = "Contains"
pack1_te1_id = "Internal torque"
pack1_te2_id = "Launch control RPM"
pack1_te3_id = "Shifting speed D+S+M Upshift/downshift reduced"
pack1_te4_id = "Modified take-off"
pack2_title_id = "S1"
pack2_t1_id = "Bench from 150€ (extra)"
pack2_t2_id = "BOOT on request"
pack2_t3_id = "For trucks and Cars"
pack2_t4_id = "Extra services* from 50€"
pack3_title_id = "S2"
pack3_t1_id= "Hybrid/upgrade turbos"
pack3_t2_id= "DECAT or DPF/EGR off on request"
pack4_title_id = "S3"
pack4_t1_id = "Include EGR+DPF off or DECAT"
pack4_t2_id = "Bench from 150€ (extra)"
pack4_t3_id = "BOOT on request"
pack4_t4_id = "Extra services* from 50€"
pack5_title_id = "Extra services (S1-S2-S3)"
pack5_t1_id = "VMAX OFF from 50€ (without tuning 120€)"
pack5_t2_id = "ADBLUE OFF from 120€ (without tuning 240€)"
pack5_t3_id = "START/STOP System off from 20€ (without tuning 60€)"
pack5_t4_id = "Pops and Bangs from 260€ (only DECAT Stage 3)"
pack5_t5_id = "Launch Control from 60€ (without Tuning 120€)"
pack5_t6_id = "Warm and Cold Startt off from 50€ (only stage 3)"
pack6_title_id = "Extra services (only S3)"
pack6_t1_id = "Include EGR+DPF off or DECAT"
pack6_t2_id = "Bench from 150€ (extra)"
pack6_t3_id = "BOOT on request"
pack6_t4_id = "Extra services* from 50€"


become = "Become our dealer"
contact_tab_id = "CONTACT"
contact = "Contact us"

become_text_id = "Join us and take advantage of the opportunities offered in our Programme. Click on the button to start to know more about!"
form_title_id = "Fill this form and we will puit in contact with you"
form_1_id = "Full name"
form_2_id = "Email or phone number"
form_3_id = "Message"
contact_id = "Contact us"
insta_clients = "Ask our clients"
insta_id = "Follow us"
sent = "Your form has been send!"
done = "Done"


