about_tab_id = "INICIO"
about_main_title_id = "Optimiza tu coche con chip tuning"
about_main_text1_id = "Chip tuning es el proceso de actualización de la unidad de control electrónico de un vehículo para lograr un mejor rendimiento y mejor economía de combustible con menos emisiones"
about_main_text2_id = "Este chip de funcionamiento incrementa radicamente los caballos de potencia. No perjudica ni daña tu motor, sino que esta diseñado para trabajar de una manera favorable y sostenible para tu coche, sin importar que sea de gasolina o diesel"
your_id = "Tu coche necesitará un remapping"
your_text_id = "Tambien llamado Remapping (ECU REMAP), el chiptuning ofrece muchas opciones para hacer que tu coche desarrolle un alto nivel de rendimiento y capacidad a nivel tecnologico para adaptarse al futuro. Cualquier coche de cualquier marca puede ser reprogramado para convertirse en una version mejorada, que proporciona por ejemplo suavidad en la marca o romper con las limitaciones de pontencia de fábrica"
works_id = "¿Cómo funciona el Chip Tuning?"
works_text_id = "Estas modificaciones o ajustes se concentran en archivos de ajuste de chip. Cada uno esta diseñado y generado por ingenieros, programadores y sintonizadores con experiencia"
works_text2_id = "Los archivos de ajuste tambien se llaman archivos de calibracion y su contenido,  personalizado para el cliente, esta creado y  esta listo para ser instalado y activado en el ECU de su coche. Sencillamente los archivos desbloquean automaticamente el verdadero potencial de tu coche"
install_id = "¿Cómo se instala Chip tuning?"
install_text_id = "Con la ayuda de un dispositivo programador (BDM, EOBD, EOBD CAN-BUS, K-LINE, PWM EOBD) y previamente configurado, se conecta directamente entre tu ECU y el sistema de sensores. No hace falta abrir la unidad de control de tu equipo ni tocar otro elemento del coche. El intercambio de datos se produce al conectar ese pequeño dispositivo"
install_text2_id = "El dispositivo actua como un microprocesador y es compatible con cualquier ECU de cualquier coche. Nada se va a desconfigurar o desestabilizar, sólo mejorará los parámetros de fábrica del motor"
serv_tab_title_id = "SERVCIOS"
file_title_id = "Archivos de ajuste"
file_text_id = "Los archivos de ajuste son 100% personalizables, con mejor rendimiento, adaptado para ti, que aporta menor consumo de combustible y una reasignacion segura del motor. Todo ello se convierte en un beneficio real gracias al trabajo de optimizacion del chip"
soft_optim_title_id = "Optimización software"
soft_optim_text1_id = "La optimización del software del motor se desarrolla para crear un coche más potente mediante el procedimiento de chiptuning. Afinar el software de su motor y caja de cambios significa añadir un enorme valor para su coche a largo plazo"
soft_optim_text2_id = "Está comprobado: las características mejoran rápidamente como, por ejemplo, la suavidad de marcha o las vibraciones en la transición o al arrancar"
dyno_title_id = "Test Dyno-Road"
dyno_text1_id = "Es un banco de pruebas en carretera que mide la potencia, el eje de torsión, la aceleración y otros parámetros de los turismos y otros vehículos de combustión o eléctricos. Simulará situaciones de carga especiales con nuestro equipo de banco de pruebas en carretera, con el fin de garantizar la estabilidad de su vehículo"
dyno_text2_id = "Analizamos con nuestro dinamómetro el comportamiento de conducción del coche a través de extensas pruebas en carretera - para que el confort y el rendimiento encajen. Con este servicio podremos saber qué hacer a continuación, para maximizar la potencia de su vehículo y poder diagnosticar los ajustes que necesita"
device_inst_title_id = "Instalación del dispositivo en casa"
device_inst_text1_id = "¿Nuestras instalaciones están demasiado lejos para usted? Facilitamos las cosas pensando en la comodidad de nuestros clientes. Pida el sistema deseado y más adecuado para el auto-montaje o incluso utilice nuestra creciente red de sintonizadores para la instalación en su área"
device_inst_text2_id = "También podemos ir hasta usted y optimizar su coche directamente en su garaje. Sólo será necesaria la electricidad y la conexión wifi. Si su coche está parado la mayor parte del tiempo, o en diferentes lugares, nos adaptamos para ofrecerle el mejor servicio"
device_inst_text3_id = "* También somos conscientes de la importancia de respetar las medidas sanitarias a la hora de realizar un servicio a domicilio, teniendo en cuenta la seguridad, higiene y protección necesarias debido al Coronavirus"
why_title_id = "Quienes somos"
why_text1_id = "En AP-chip, un equipo en permanente crecimiento de ingenieros experimentados, diseñadores y mecánicos profesionales trabajan en estrecha colaboración para ofrecer los mejores servicios de software y entrega a medida"
why_text2_id = "Debido a la continua mejora, siempre puedes beneficiarte de nuestra experiencia y equipo de expertos. Nuestros metodos de desarrollo estan basados en nuestra pasion por los coches y nuestra dedicacion a aprender y a implementar los último en tecnologia para los vehiculos de nuestros clientes"
why_text3_id = "Con un compromiso total, nos ocupamos de usted en cualquier situación, ya sea en el circuito o en la carretera; con nuestro apoyo individual, estará bien preparado para cualquier situación a la que se enfrente el rendimiento de su vehículo"
become_tab_id = "HAZTE TUNER"
become_boxinfo1_id = "Servicios de archivos chip tuning a nivel mundial"
become_boxinfo2_id = "25 minutos de duración de servicio"
become_boxinfo3_id = "1112 clientes"
become_boxinfo4_id = "19 tuners"
become_boxinfo5_id = "1200 files a month"
become_boxinfo6_id = "Potente base de datos"
become_boxinfo7_id = "El mejor ECU Remap"
become_boxinfo8_id = "Soluciones inteligentes"
become_boxinfo9_id = "Servicio profesional"
become_boxinfo10_id = "Modificaciones en los archivos Chip tuning"
buy_title_id = "Compra archivos chip tuning en 4 sencillos, rápidos y seguros pasos"
buy_step1_tittle_id ="PASO 1: REGISTRATE"
buy_step1_text_id = "Registra su cuenta gratuitamente. El registro es obligatorio si quieres subir y recibir archivos chip tuning"
buy_step2_title_id = "PASO 2: COMPRA TOKENS"
buy_step2_text_id = "Compra tuning Tokens de manera segura usando PayPal o tarjeta de crédito. Obten tu factura de inmediato"
buy_step3_title_id = "PASO 3: ABRE EL SERVICIO DE ARCHIVOS"
buy_step3_text_id = "Encuentra el archivo que necesitas"
buy_step4_title_id = "PASO 4: DESCÁRGALO"
buy_step4_text_id = "Descarga tu archivo chip tuning modificado"
price_title_id = "Precios"
contains = "Contiene"
pack1_title_id= "GTS"
pack1_te1_id = "Par interno"
pack1_te2_id = "Control de lanzamiento RPM"
pack1_te3_id ="Velocidad de cambio D+S+M reducción de la velocidad de cambio alza/baja"
pack1_te4_id = "Take-off o despegue modificado"
pack2_title_id = "S1"
pack2_t1_id = "Banco a partir de 150€ (extra)"
pack2_t2_id = "Arranque a petición"
pack2_t3_id = "Para camiones y coches"
pack2_t4_id = "Servicios extra desde 50€"
pack3_title_id = "S2"
pack3_t1_id= "Turbos híbridos"
pack3_t2_id= "DECAT o DPF/EGR"
pack4_title_id = "S3"
pack4_t1_id = "Incluye EGR+DPF off o DECAT"
pack4_t2_id = "Banco a partir de 150€ (extra)"
pack4_t3_id = "Arranque a petición"
pack4_t4_id = "Servicios extra desde 50€"
pack5_title_id = "Extra services (S1-S2-S3)"
pack5_t1_id = "VMAX OFF desde 50€ (sin tuning 120€)"
pack5_t2_id = "ADBLUE OFF desde 120€ (sin tuning 240€)"
pack5_t3_id = "START/STOP System off desde 20€ (sin tuning 60€)"
pack5_t4_id = "Pops/Bangs desde 260€ (sólo DECAT S3)"
pack5_t5_id = "Control de lanzamiento desde 60€ (sin tuning 120€)"
pack5_t6_id = "Warm y Cold Startt off desde 50€ (solo S3)"
pack6_title_id = "Servicios extra (S3)"
pack6_t1_id = "Incluye EGR+DPF off o DECAT"
pack6_t2_id = "Banco a partir de 150€ (extra)"
pack6_t3_id = "Arranque a petición"
pack6_t4_id = "Servicios extra desde 50€"
contact_tab_id = "CONTACTO"
become_text_id = "Únete a aprovecha las oportunidades ofrecidas en nuestro Programa como Tuner. Pincha para saber más"
form_title_id = "Rellene este formulario y nos pondremos en contacto con usted"
form_1_id = "Nombre completo"
form_2_id = "Email o número de teléfono"
form_3_id = "Mensaje"
contact_id = "Contáctanos"
insta_clients = "Pregunta a nuestros clientes"
insta_id = "Síguenos"
become = "Conviértete en nuestro distribuidor"
sent = "El formulario ha sido enviado!"
done = "Volver"
